server:
  port: 8089 # Usaremos el puerto 8089 para evitar colisiones
  servlet:
    context-path: /gestion-oficinas

spring:
  application:
    name: gestion-oficinas-java

  # Base de datos H2 en memoria (No requiere instalación ni Docker)
  datasource:
    url: jdbc:h2:mem:gestion_oficinas_db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

azure:
  activedirectory:
    tenant-id: "tu-id"
    client-id: "tu-id"
    client-secret: "tu-clave"

sharepoint:
  site-id: "://sharepoint.com,id,id"
