server:
  port: 8089 # Puerto libre para esquivar el Nginx de Kubernetes Kind
  servlet:
    context-path: /gestion-oficinas

spring:
  application:
    name: gestion-oficinas-java

  # Base de datos en memoria (Autocreada en RAM)
  datasource:
    url: jdbc:h2:mem:gestion_oficinas_db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  # DESACTIVAR INICIALIZADOR POR SCRIPT (Evita que lea data.sql)
  sql:
    init:
      mode: never # <-- Cambiado de 'always' a 'never'

  # Configuración del motor de persistencia (Hibernate / JPA)
  jpa:
    hibernate:
      ddl-auto: create # Genera las tablas limpias al arrancar de forma nativa
    show-sql: true     # Muestra las consultas SQL en la consola
    defer-datasource-initialization: false # <-- Cambiado a false porque ya no hay script que esperar


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
# Credenciales para el acceso automatizado al SharePoint Corporativo (Vacías para pruebas locales)
azure:
  activedirectory:
    tenant-id: ""
    client-id: ""
    client-secret: ""

# Identificador del sitio de SharePoint asignado a la oficina técnica
sharepoint:
  site-id: ""
